name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Maven (JDK 17)

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: ./mvnw test -B -V --no-transfer-progress -D"license.skip=true"

      - name: Run Checkov (IaC security scan)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: cli

      - name: Run Trivy (Filesystem scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .